import { Cars } from './cars';
export const carsList: Cars[] = [
    {
        id: 1,
        name: 'Corolla',
        imageLink: "assets/corolla.png", 
        price: "19600$",
        description: '1',
        model: 1,
    },
    {
        id: 2,
        name: 'Camry',
        imageLink: 'assets/camry.png', 
        price: "24400$",
        description: '2',
        model: 2,
    },
    {
        id: 3,
        name: 'Avalon',
        imageLink: 'assets/avalon.png', 
        price: "35870$",
        description: '3',
        model: 3,
    },
    {
        id: 4,
        name: 'Rav4',
        imageLink: 'assets/rav4.png', 
        price: "25940$",
        description: '4',
        model: 4,
    },
    {
        id: 5,
        name: 'Highlander',
        imageLink: 'assets/highlander.png', 
        price: "38200$",
        description: '5',
        model: 5,
    },
    {
        id: 6,
        name: 'Land Cruiser',
        imageLink: 'assets/lc.png', 
        price: "85415$",
        description: '6',
        model: 6,
    },
    {
        id: 7,
        name: 'Sequoia',
        imageLink: 'assets/sequoia.png', 
        price: "49990$",
        description: '7',
        model: 7,
    },
]