# Generated by Django 3.0.5 on 2020-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='imageLink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ManyToManyField(to='api.Car')),
            ],
        ),
    ]
