# Generated by Django 3.0.5 on 2020-04-28 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200426_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='new',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='api.Model'),
        ),
    ]
